enum TerrortoryType {
  STATE = 1,
  UNION_TERRORTORY = 2,
}

export const regions = [
  { id: 1, name: "Andhra Pradesh", type: TerrortoryType.STATE },
  { id: 2, name: "Arunachal Pradesh", type: TerrortoryType.STATE },
  { id: 3, name: "Assam", type: TerrortoryType.STATE },
  { id: 4, name: "Bihar", type: TerrortoryType.STATE },
  { id: 5, name: "Chhattisgarh", type: TerrortoryType.STATE },
  { id: 6, name: "Goa", type: TerrortoryType.STATE },
  { id: 7, name: "Gujarat", type: TerrortoryType.STATE },
  { id: 8, name: "Haryana", type: TerrortoryType.STATE },
  { id: 9, name: "Himachal Pradesh", type: TerrortoryType.STATE },
  { id: 10, name: "Jharkhand", type: TerrortoryType.STATE },
  { id: 11, name: "Karnataka", type: TerrortoryType.STATE },
  { id: 12, name: "Kerala", type: TerrortoryType.STATE },
  { id: 13, name: "Madhya Pradesh", type: TerrortoryType.STATE },
  { id: 14, name: "Maharashtra", type: TerrortoryType.STATE },
  { id: 15, name: "Manipur", type: TerrortoryType.STATE },
  { id: 16, name: "Meghalaya", type: TerrortoryType.STATE },
  { id: 17, name: "Mizoram", type: TerrortoryType.STATE },
  { id: 18, name: "Nagaland", type: TerrortoryType.STATE },
  { id: 19, name: "Odisha", type: TerrortoryType.STATE },
  { id: 20, name: "Punjab", type: TerrortoryType.STATE },
  { id: 21, name: "Rajasthan", type: TerrortoryType.STATE },
  { id: 22, name: "Sikkim", type: TerrortoryType.STATE },
  { id: 23, name: "Tamil Nadu", type: TerrortoryType.STATE },
  { id: 24, name: "Telangana", type: TerrortoryType.STATE },
  { id: 25, name: "Tripura", type: TerrortoryType.STATE },
  { id: 26, name: "Uttar Pradesh", type: TerrortoryType.STATE },
  { id: 27, name: "Uttarakhand", type: TerrortoryType.STATE },
  { id: 28, name: "West Bengal", type: TerrortoryType.STATE },
  {
    id: 29,
    name: "Andaman and Nicobar Islands",
    type: TerrortoryType.UNION_TERRORTORY,
  },
  { id: 30, name: "Chandigarh", type: TerrortoryType.UNION_TERRORTORY },
  {
    id: 31,
    name: "Dadra and Nagar Haveli and Daman and Diu",
    type: TerrortoryType.UNION_TERRORTORY,
  },
  { id: 32, name: "Lakshadweep", type: TerrortoryType.UNION_TERRORTORY },
  { id: 33, name: "Delhi", type: TerrortoryType.UNION_TERRORTORY },
  { id: 34, name: "Puducherry", type: TerrortoryType.UNION_TERRORTORY },
  { id: 35, name: "Ladakh", type: TerrortoryType.UNION_TERRORTORY },
  { id: 36, name: "Jammu and Kashmir", type: TerrortoryType.UNION_TERRORTORY },
];
