import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProviders } from "@/components/ThemeToggle/Provider";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { Toaster } from "@/components/ui/sonner";
import { UserProvider } from "@/context/userContext";

const geistSans = localFont({
  src: "../assets/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../assets/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-gray-100 dark:bg-black text-gray-600 dark:text-gray-300 overflow-y-scroll`}
      >
        <GoogleOAuthProvider
          clientId={process.env.NEXT_PUBLIC_GOOGLE_AUTH ?? ""}
        >
          <UserProvider>
            <ThemeProviders>{children}</ThemeProviders>
          </UserProvider>
        </GoogleOAuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
